### ISSUE TITLE
[JOSS REVIEW] Several questions 

### ISSUE THREAD

**Issue by KedoKudo** [LightForm-group/xrdfit#38]
Hi @merrygoat and @christopher-daniel, 

I have several questions regarding your package `xrdfit`, and I think addressing them can help it reach a larger audience in the long run

* Benchmark comparison
Have you performed any benchmark comparison for `xrdfit` with other similar software(s) in the field?  It would be helpful to let users know its performance and (potentially) scalability so that they can decide whether it is suitable for their data.

* JOSS paper related
    * The DOI listed in the paper does not exist (typo perhaps?)
    * Once the preprint (Direct Evidence for a Dynamic Phase Transformation during High Temperature Deformation in Ti-64) published, please update the reference section accordingly

* Distributed computing
So far it seems like `xrdfit` is a single node application.  Will it provide parallel capabilities (MPI) in the future?

**Comment by merrygoat** [comment]
Thank you for your comments.

- We haven't made direct comparisons to other software. As I understand, similar software (MAUD being one example) tends to base fits on an underlying model of the scattering mechanism whereas `xrdfit` takes the simpler approach of fitting the raw data without considering the underlying model of scattering. I agree that it would be a good idea to add some approximate information about performance and scaling to the documentation and have opened issue #43. Perhaps @christopher-daniel could comment on other software in the field and their approach?

- I think all of the DOIs in the paper work correctly. Could you provide more information on which one is broken? We will update the reference to `Direct Evidence for a Dynamic Phase Transformation` if it is published before `xrdfit`.

- Yes, you are correct, it is single core. I have found implementing multiple processing difficult (the weakness of Python!). 

The fitting of multiple time steps cannot be done in parallel, since the start point of each fit depends on the last step and so they must be carried out in order.

The fitting of the different peaks within a single pattern should be possible to run over multiple cores and I consider this in issue #28 (test code is in the multiprocessing branch). The problem is that this makes performance slower than running single core, I think because each fit is modest (~ 2 seconds), the overhead is greater than the computation. I will continue investigating a little more as it may be a weakness in my implementation, though I don't see anything obvious.

For performance in general. profiling shows 95% of the performance time in `xrdfit` is taken by lmfit. lmfit is a layer to the scipy.optimize.curve_fit function and so has some overhead. It should be possible to directly implement the fitting using SciPy to remove this overhead. However, profiling shows that the overhead of lmfit in this case is not large - perhaps 20-30% overall, so I  do not think that this change would be transformative. Since lmfit provides many convenience functions, greatly reducing the complexity of the code, I think that the performance cost is worth it.

Using something like MPI would require stepping outside Python to write fitting functions and I think that is beyond the scope of this project (and beyond my abilities!).

**Comment by christopher-daniel** [comment]
It is possible to run single peak fitting in [DAWN](https://dawnsci.org), an in-house software developed at Diamond Light Source. This is briefly mentioned in the paper introduction, as well as mentioned in the notebooks describing the initial 'caking' of the data. There is also [Polydefix](http://merkel.texture.rocks/Multifit-Polydefix/?lang=en), although I am less familiar with this software. But, in both cases, the software is a compiled package and uses a GUI. So, the peak fitting in DAWN involves a point and click method to select the peak bounds, meaning it isn't necessarily a reproducible analysis. This does an ok job for small datasets with clearly defined peaks, but would clearly take a long time for any systematic analysis of many different tests or cakes. However, and most importantly, it is difficult to clearly distinguish any multiple peaks with any crossover using DAWN, with the peak fits either merging into one, or an error message appearing asking the user to redefine the peak bounds each time. This really makes any analysis fitting multipeaks in datasets containing 1000s of patterns impossible with these current available software.

MAUD is a different software which does a different job. This uses a Rietveld refinement method to match a model of the material properties (and the beamline setup) to the data. This is great for determining things like the phase fraction and crystal orientation, etc. But, because MAUD uses a model of the unit cell to fit the data, there is some averaging of the overall fit and a larger error in the individual peak position. So, we really need xrdfit for an accurate single peak fitting of the individual lattice plane peaks, to determine their peak position and the peak shifts over time, which is used to calculate the micromechanical behaviour.

I will run some quick (rough) benchmark tests for a single peak fit in DAWN and compare this to xrdfit.

**Comment by KedoKudo** [comment]
@merrygoat and @christopher-daniel,  thanks for the detailed explanation.  I am looking forward to the benchmark results 😄

**Comment by merrygoat** [comment]
Sorry, forgot to update this. More information on other packages was added in 03ba476242599d3b5c97468c8d61213d917966fb and some information on performance in 854d69eb9a204db4f8082273a2dc50657a6a8d1c. 

The good news is that xrdfit is quicker both in speed of analysis (very approximately 20 times quicker than DAWN)  but also quicker to set up the workflow to measure many peaks.
