### ISSUE TITLE
[JOSS REVIEW] Enhancement suggestions

### ISSUE THREAD

**Issue by KedoKudo** [LightForm-group/xrdfit#39]
Hi @merrygoat and @christopher-daniel,

After testing `xrdfit` locally, I would like to make the following enhancement suggestions:

- [x]  Put the repo on Binder (https://mybinder.org) or Colab (colab.research.google.com) so that others can directly test them in the browser without installing

- [x]  Installation instructions
    * please use either `pip freeze` or `conda env export` to generate `requirement.txt` so that it contains necessary version information
    * according to my test, `xrdfit` also needs `ipywidgets` to function properly in JupyterLab, otherwise an error will occur in the 3rd example notebook.

- [x]  add unit testing
please consider adding testing (unit testing) to `xrdfit`.

- [x] add community guideline
It would be helpful to have a community guideline (such as code of conduct, how to contribute to the project) for `xrdfit`.

**Comment by merrygoat** [comment]
I have added CODE_OF_CONDUCT.md along with the existing CONTRIBUTING.md

I don't think I have the knowledge to usefully add unit testing. I could test simple things like function arguments types and return types, though I feel this is mostly covered by the function type hints. A lot of the the functionality of the methods is then either plotting or fitting, both of which I don't know how I would test at a function level since there is no real "right" answer. A good fit is, to some extent, the one that looks good. I would be pleased for suggestions about a good way to do this though.

I treat the tutorial notebooks as informal integration tests, since they use all aspects of the program and we run through them each time we make a release to make sure everything is behaving as expected.

**Comment by KedoKudo** [comment]
@merrygoat Thanks for implementing the suggestions.  I'm closing this issue now 😄
